# Generated by Django 3.0.6 on 2020-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unemployed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unemployed',
            name='cv',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='itm_documents',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
