# Generated by Django 3.0.6 on 2020-05-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unemployed', '0003_auto_20200509_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unemployed',
            name='cv',
            field=models.BinaryField(blank=True, editable=True),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='itm_documents',
            field=models.BinaryField(blank=True, editable=True),
        ),
    ]
