# Generated by Django 3.0.6 on 2020-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unemployed', '0004_auto_20200509_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unemployed',
            name='cv',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='itm_documents',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
