# Generated by Django 3.0.6 on 2020-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unemployed', '0005_auto_20200509_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unemployed',
            name='cv',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='itm_documents',
            field=models.TextField(blank=True),
        ),
    ]
