# Generated by Django 3.0.6 on 2020-05-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unemployed', '0006_auto_20200509_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unemployed',
            old_name='itm_documents',
            new_name='itmDocuments',
        ),
    ]
