# Generated by Django 3.0.6 on 2020-05-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unemployed', '0008_auto_20200509_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unemployed',
            name='dateOfBirth',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
