# Generated by Django 3.0.6 on 2020-05-09 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalMin', models.IntegerField()),
                ('intervalMax', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='revenueId',
        ),
        migrations.AddField(
            model_name='company',
            name='revenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Revenue'),
        ),
    ]
