# Generated by Django 3.0.6 on 2020-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200509_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
