# Generated by Django 3.0.6 on 2020-05-10 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unemployed', '0002_auto_20200510_0747'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.Skill')),
                ('unemployed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unemployed.Unemployed')),
            ],
        ),
    ]
